# Generated by Django 6.0.5 on 2026-05-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename_or_endpoint', models.CharField(max_length=255)),
                ('raw_payload_snapshot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('facility_identifier', models.CharField(max_length=100)),
                ('raw_value_reported', models.DecimalField(decimal_places=4, max_digits=15)),
                ('raw_unit_reported', models.CharField(max_length=20)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('calculated_co2e_kg', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
                ('system_flags', models.JSONField(default=list)),
                ('analyst_notes', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.dataingestionbatch')),
            ],
        ),
    ]
