services:
  - type: web
    name: breathe-esg-backend
    env: python
    buildCommand: "python -m pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput && python backend/manage.py migrate && python backend/manage.py seed_data"
    startCommand: "gunicorn --chdir backend esg_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
